version: "3.9"
services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "$INT:5432:5432"

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "$INT:6379:6379"
    volumes:
      - "./redis-persistence:/data"

  rabbitmq:
    image: "rabbitmq:3.8.14-management"
    container_name: rabbitmq
    hostname: 'dev-rabbitmq'
    environment:
      - "RABBITMQ_PASSWORD=thisISrabbitPASS123"
      - "RABBITMQ_USERNAME=admin"
      # - ./rabbitmq/config/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    volumes:
      - './rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    ports:
      # HTTP management UI
      - "$INT:15672:15672"
      # AMQP protocol port
      - "$INT:5672:5672"