version: "3.9"
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "$INT:5432:5432"

  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    restart: always
    command: /opt/bitnami/scripts/redis/run.sh --appendonly no
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "$INT:6379:6379"
    volumes:
      - "./redis-persistence:/bitnami/redis/data:rw"

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    environment:
      - "RABBITMQ_PASSWORD=thisISrabbitPASS123"
      - "RABBITMQ_USERNAME=admin"
      - ./config/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    ports:
      # HTTP management UI
      - "$INT:15672:15672"
      # AMQP protocol port
      - "$INT:5672:5672"