"""003_adding_unique_constraint

Revision ID: 914a5aff1eb2
Revises: aab222911f8d
Create Date: 2022-07-15 03:24:37.809064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914a5aff1eb2'
down_revision = 'aab222911f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coins_coin_id', table_name='coins')
    op.create_index(op.f('ix_coins_coin_id'), 'coins', ['coin_id'], unique=True)
    op.create_unique_constraint('uc_coin_id_contract_address', 'coins_contract', ['coin_id', 'contract_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_coin_id_contract_address', 'coins_contract', type_='unique')
    op.drop_index(op.f('ix_coins_coin_id'), table_name='coins')
    op.create_index('ix_coins_coin_id', 'coins', ['coin_id'], unique=False)
    # ### end Alembic commands ###
