"""001_init_tables

Revision ID: aab222911f8d
Revises: 
Create Date: 2022-07-13 16:23:18.401958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab222911f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(), nullable=True),
    sa.Column('coin_symbol', sa.String(), nullable=True),
    sa.Column('coin_name', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_coin_id'), 'coins', ['coin_id'], unique=False)
    op.create_index(op.f('ix_coins_coin_symbol'), 'coins', ['coin_symbol'], unique=False)
    op.create_table('coins_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_contract_contract_address'), 'coins_contract', ['contract_address'], unique=False)
    op.create_index(op.f('ix_coins_contract_platform'), 'coins_contract', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_contract_platform'), table_name='coins_contract')
    op.drop_index(op.f('ix_coins_contract_contract_address'), table_name='coins_contract')
    op.drop_table('coins_contract')
    op.drop_index(op.f('ix_coins_coin_symbol'), table_name='coins')
    op.drop_index(op.f('ix_coins_coin_id'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
