"""adding decimals column

Revision ID: afd5a406a0c2
Revises: dc7a3aebac1e
Create Date: 2022-07-15 03:52:03.005157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd5a406a0c2'
down_revision = 'dc7a3aebac1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins_contract', sa.Column('decimals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins_contract', 'decimals')
    # ### end Alembic commands ###
