"""adding watch for price

Revision ID: d6ee8aa40732
Revises: afd5a406a0c2
Create Date: 2022-07-15 16:57:25.463546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ee8aa40732'
down_revision = 'afd5a406a0c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('watch_for_price', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'watch_for_price')
    # ### end Alembic commands ###
