"""adding_not_null_to_contract_address_and_platform

Revision ID: dc7a3aebac1e
Revises: e42ec43ce4f8
Create Date: 2022-07-15 03:37:07.564769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7a3aebac1e'
down_revision = 'e42ec43ce4f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coins_contract', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('coins_contract', 'contract_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coins_contract', 'contract_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coins_contract', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
