"""chainging_coin_id_to_platform_in_uc

Revision ID: e42ec43ce4f8
Revises: 914a5aff1eb2
Create Date: 2022-07-15 03:30:26.990609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42ec43ce4f8'
down_revision = '914a5aff1eb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_coin_id_contract_address', 'coins_contract', type_='unique')
    op.create_unique_constraint('uc_platform_contract_address', 'coins_contract', ['platform', 'contract_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_platform_contract_address', 'coins_contract', type_='unique')
    op.create_unique_constraint('uc_coin_id_contract_address', 'coins_contract', ['coin_id', 'contract_address'])
    # ### end Alembic commands ###
